spring:
  application:
    name: sokdak

  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/sokdak?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:ehrtnfl99@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o-mini}

    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      embedding:
        model: bge-m3

    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: 6334
        use-tls: false
        collection-name: prompts
        initialize-schema: false

server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

  servlet:
    session:
      cookie:
        secure: true
        same-site: none

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
